# Generated by Django 3.2.5 on 2021-07-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210704_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfood',
            old_name='medicine',
            new_name='food',
        ),
    ]
