# Generated by Django 3.2.5 on 2021-07-05 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_rename_medicine_orderfood_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.RenameModel(
            old_name='Food',
            new_name='Medicine',
        ),
        migrations.DeleteModel(
            name='OrderFood',
        ),
        migrations.AddField(
            model_name='ordermedicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.medicine'),
        ),
        migrations.AddField(
            model_name='ordermedicine',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='medicines',
            field=models.ManyToManyField(through='common.OrderMedicine', to='common.Medicine'),
        ),
    ]
