# Generated by Django 3.2.5 on 2021-07-05 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20210705_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='medicines',
        ),
        migrations.RenameModel(
            old_name='Medicine',
            new_name='Food',
        ),
        migrations.DeleteModel(
            name='OrderMedicine',
        ),
        migrations.AddField(
            model_name='orderfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.food'),
        ),
        migrations.AddField(
            model_name='orderfood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(through='common.OrderFood', to='common.Food'),
        ),
    ]
